workspace(name = "bazel_bats_integration")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

BAZEL_BATS_VERSION = "0.29.1"

HEAD = "9ea10a4638ca49e26e779d01efafbf3a25ee5215"

http_archive(
    name = "bazel_bats",
    sha256 = "7633d79b3dfa52a3b822129c44b5ed83ab3b6dbb520056b7a3d0366177673d1d",
    # TODO: Tag and release HEAD.
    # strip_prefix = "bazel-bats-%s" % BAZEL_BATS_VERSION,
    strip_prefix = "bazel-bats-%s" % HEAD,
    urls = [
        # TODO: Tag and release HEAD.
        # "https://github.com/jmelahman/bazel-bats/archive/refs/tags/v%s.tar.gz" % BAZEL_BATS_VERSION,
        "https://github.com/jmelahman/bazel-bats/archive/%s.tar.gz" % HEAD,
    ],
)

load("@bazel_bats//:deps.bzl", "bazel_bats_dependencies")

bazel_bats_dependencies(
    sha256 = "36a3fd4413899c0763158ae194329af8f48bb1ff0d1338090b80b3416d5793af",
    version = "1.5.0",
)
